<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-2Q75ANP" failures="1" tests="6" name="Test" time="10.156" errors="0" timestamp="2024-04-25T08:51:44 IST">
  <testcase classname="PageTest.HomeTest" name="validateTitle" time="0.067"/>
  <testcase classname="PageTest.HomeTest" name="navToSingleMalt" time="1.18"/>
  <testcase classname="PageTest.ProductTest" name="validateFilter" time="1.39">
    <failure type="java.lang.AssertionError" message="expected [1] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [2]
at PageTest.ProductTest.validateFilter(ProductTest.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- validateFilter -->
  <testcase classname="PageTest.ProductTest" name="resetFilterValidation" time="0.849"/>
  <testcase classname="PageTest.ProductTest" name="sortingFilter" time="2.994"/>
  <testcase classname="PageTest.ProductTest" name="navToProduct" time="2.715"/>
  <testcase classname="PageTest.BaseTest" name="@AfterSuite tearDown" time="0.0">
    <ignored/>
  </testcase> <!-- @AfterSuite tearDown -->
  <testcase classname="PageTest.BaseTest" name="@BeforeSuite initBrowser" time="0.0">
    <ignored/>
  </testcase> <!-- @BeforeSuite initBrowser -->
</testsuite> <!-- Test -->
